# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cc75d3feb51a6ce07e16e3f668a6dbecd480b7674f7ff88aa7fa08d98a23773409a6f8fd85245fe380fe39d6fbfafc21d7ba5aa6d52b5badf339fe71d29c567

test:
  secret_key_base: 0bd857cf5b070449bbb33da66e05e71cf2f9312334a1356f841b0cbcf50a2645e64cae491803fa3d776fba7e9a59b0bb776df71a0d81a790dae6131d701d664c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
